import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import type { Metadata } from 'next'

import { roboto } from '@/theme/app-font'

import { AppTheme } from '../theme/app-theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      {/* https://mui.com/material-ui/integrations/nextjs/#font-optimization */}
      <body suppressHydrationWarning className={roboto.variable}>
        <AppRouterCacheProvider>
          <AppTheme>
            {children}
          </AppTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
