import { CssBaseline } from '@mui/material'
import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'

import { Roboto } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles'
import { theme } from './theme'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body suppressHydrationWarning className={roboto.variable}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {/* https://web.dev/articles/color-scheme */}
            {/* https://mui.com/material-ui/react-css-baseline/#color-scheme */}
            {/* https://mui.com/material-ui/customization/dark-mode/#:~:text=Adding%20%3CCssBaseline%20/%3E%20inside%20of%20the%20%3CThemeProvider%3E%20component%20will%20also%20enable%20dark%20mode%20for%20the%20app%27s%20background. */}
            <CssBaseline enableColorScheme />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
